// generated/Badge.broken.tsx
import { resolveToken } from './tokenResolver';

export interface BadgeProps {
  state: 'default' | 'danger';
  size: 'sm' | 'md' | 'lg';
  children: React.ReactNode;
}

export const Badge = ({ state, size, children }: BadgeProps) => {
  return (
    <span style={{ background: resolveToken('color/red/999'), borderRadius: resolveToken('radius/sm') }}>
      {children}
    </span>
  );
};

// generated/Badge.angular.broken.ts
import { Component, Input } from '@angular/core';
import { NgStyle } from '@angular/common';
import { resolveToken } from './token-resolver';

@Component({
  selector: 'app-badge',
  standalone: true,
  imports: [NgStyle],
  template: `
    <span [ngStyle]="badgeStyle">
      <ng-content></ng-content>
    </span>
  `,
})
export class BadgeComponent {
  @Input() state: 'default' | 'danger' = 'default';
  @Input() size: 'sm' | 'md' | 'lg' = 'sm';

  get badgeStyle(): Record<string, string> {
    return {
      background: resolveToken('color/red/999'),
      borderRadius: resolveToken('radius/sm'),
    };
  }
}
